const mockArticles = [
  {
    id: "c6022020-da91-455f-87f2-32ab31ffae6a",
    title: "Great Eclipse of 1876",
    author: "Dr. Elias Thornwood",
    dateOfPublication: "1992-06-15",
    text: "In the summer of 1876, an unexpected solar eclipse plunged the world into darkness for an unprecedented twelve hours. Scientists scrambled to explain the anomaly, while religious leaders claimed it was a sign of divine intervention. It was later discovered that a rogue celestial body had temporarily obscured the sun, causing panic and reshaping global superstitions. Meanwhile, strange meteorological phenomena were recorded, with areas experiencing unnatural weather patterns ranging from snowstorms in tropical regions to heatwaves in the poles. Many believed this event heralded the dawning of a new age, leading to widespread prophetic movements. The eclipse also triggered a worldwide surge in spiritualism, with people claiming to experience visions and contact with celestial beings during the brief darkened hours. The shadow cast by this eclipse never truly lifted from humanity’s collective consciousness, prompting further astronomical explorations for decades to come.",
  },
  {
    id: "bb9007ce-8f1a-454c-8f05-a7bad6b9dcda",
    title: "Year Without Time",
    author: "Professor Alistair Wren",
    dateOfPublication: "1981-09-30",
    text: "During the year 1794, an unexplained distortion in Earth's temporal field caused clocks to malfunction, calendars to reset randomly, and night and day to lose all consistency. Scholars and philosophers debated whether time itself had ceased to exist. The event ended abruptly on January 1, 1795, without explanation, leaving historians to call it 'The Forgotten Year.' However, some records suggest that pockets of individuals experienced time differently, with some regions of the world remaining trapped in perpetual twilight, while others experienced brief flashes of future events. The anomaly sparked various cults that claimed to hold knowledge of the true nature of time and attempted to harness its power for world domination. In the years following the event, numerous attempts to replicate the phenomenon led to the development of the first rudimentary time travel theories, though none were successful. Several ancient civilizations, such as the Mayans and the Egyptians, began to feature distorted temporal symbols in their artwork, suggesting that they, too, had experienced a brief rupture in the fabric of time.",
  },
  {
    id: "eb7499a8-ea1e-44e1-a4ff-f8cef661b9d9",
    title: "Ocean Recession of 1623",
    author: "Captain Jeremiah Blackwood",
    dateOfPublication: "1990-04-10",
    text: "In the winter of 1623, the world's oceans mysteriously receded by nearly 100 miles from all coastlines, exposing hidden ruins and ancient shipwrecks. Coastal cities were left stranded inland, leading to economic collapse and mass migrations. After three months, the seas returned overnight, leaving many questioning the very nature of the planet’s waters. Some believed the event to be the result of a vast underground river system temporarily draining, while others speculated it was a result of celestial interference. Unexplained, violent earthquakes followed the event, triggering the rise of numerous new islands in the South Pacific. The coastal nations that had once flourished saw their economies decimated, while the displaced populations sought refuge in untouched, previously uncharted lands. Later reports from those who ventured into the now-submerged regions revealed signs of an advanced civilization, whose technologies seemed far beyond anything humanity had known. Some suggested these lost civilizations were the precursors to modern humanity, lost to time and cataclysmic events. Tales of the event spread worldwide, with some groups claiming that the oceans would eventually recede again, signaling the return of an ancient race.",
  },
  {
    id: "410b02e9-2321-4e5f-91db-aa633e2c0980",
    title: "Night of the Shattered Sky",
    author: "Lady Eleanor Vexley",
    dateOfPublication: "1987-11-22",
    text: "On the night of April 3, 1844, the sky itself seemed to fracture, as enormous cracks of glowing light appeared in the heavens. Witnesses reported hearing an otherworldly hum as the cracks widened, revealing swirling voids of unknown color. After three hours, the fractures sealed themselves, but the event left a permanent scar in human consciousness. In the wake of the shattered sky, people began experiencing disturbing dreams of an impending catastrophe, while a strange phenomenon known as “skyfall” swept through Europe, causing bizarre objects to rain down from the sky. Many were convinced that the cracks were a warning, a signal from the universe that humanity’s time was drawing to a close. The event inspired an entire generation of poets, artists, and philosophers, who sought to decode the meaning of the fractured sky. Some believed it was the physical manifestation of an ancient prophecy, while others insisted it was a tear in the fabric of reality itself, allowing glimpses into parallel worlds or dimensions. The cracks in the sky have never fully been explained, though reports of similar occurrences in isolated areas have continued throughout history, fueling endless speculation about the true nature of the cosmos.",
  },
  {
    id: "440c8b1c-96e0-4faf-a9cc-fb5c32c1a1ba",
    title: "War That Never Was",
    author: "General Tobias Harkens",
    dateOfPublication: "1988-07-01",
    text: "In 1910, an entire year’s worth of newspapers, letters, and official records described an ongoing world war that, by all other accounts, never actually happened. Governments denied involvement, yet soldiers claimed to have fought battles that left no trace. Some believe an alternate reality briefly overlapped with our own before vanishing forever. Others suggest that this “war” was the result of a covert global conflict waged by secret organizations whose existence remains concealed. Ancient and obscure technologies, thought to be long lost, were purportedly used during this war, with some historians speculating that it was a conflict fought with weapons beyond human comprehension. The year itself became a black hole in historical records, with many records vanishing or being altered to erase its existence. Several conspiracy theories arose, claiming that the war had not been fought between nations, but between factions of an alien civilization that had secretly integrated with humanity. Some who studied the phenomenon claimed that the war was not a battle in space or time, but rather a war fought in the minds of individuals, affecting perceptions of reality itself.",
  },
  {
    id: "f12a3e67-8a2c-4b0e-b987-12cd87a5f324",
    title: "Phantom Battalion of 1806",
    author: "Major Edwin Blackwood",
    dateOfPublication: "1995-03-12",
    text: "During the Napoleonic Wars, an entire battalion of soldiers was seen marching through a battlefield in Prussia, only to vanish into thin air. Eyewitnesses swore they could hear their voices and muskets firing, but no trace of them was ever found. Some believe they were ghosts of fallen warriors; others think they slipped into another dimension.",
  },
  {
    id: "b77c4d99-6e49-405a-85b6-bdb892e3a8e2",
    title: "Sunken Library of Alexandria",
    author: "Dr. Helena Forsythe",
    dateOfPublication: "1994-08-21",
    text: "In 1925, divers exploring the Mediterranean near Egypt uncovered a vast underwater library filled with scrolls and tablets. The texts contained lost histories, unknown scientific theories, and even accounts of vanished civilizations. A week later, a massive storm swept through the area, and when researchers returned, the library had disappeared entirely.",
  },
  {
    id: "c449d5f8-13a4-48c6-91bd-ff63223e12d1",
    title: "Day London Slept",
    author: "Inspector Jonathan Wells",
    dateOfPublication: "1992-07-09",
    text: "On the morning of May 14, 1882, every inhabitant of London was found unconscious in their beds and homes. No one awoke until noon, and none could remember falling asleep. Doctors and scientists were baffled, and no cause was ever determined. The event was quietly buried in history, with only scattered records remaining.",
  },
  {
    id: "d58a93a1-97b1-49c4-bc6f-3f26a87e7895",
    title: "Frozen Caravan of 1432",
    author: "Sultan Hakim al-Rashid",
    dateOfPublication: "1990-11-20",
    text: "A trade caravan traveling through the Silk Road was found completely frozen in the desert, as if caught in an instant of time. Camels, merchants, and even flickering flames were encased in ice despite the blistering heat. A year later, the ice melted, leaving no remains behind.",
  },
  {
    id: "e38c24d6-53b7-4d2a-bec9-65823b5bbf7b",
    title: "Lost Hour of 1913",
    author: "Professor Walter Greaves",
    dateOfPublication: "1992-02-17",
    text: "At exactly 2:14 AM on August 6, 1913, every clock in the world skipped forward by one hour. People reported feeling disoriented, as if they had experienced an event they could not recall. No scientific explanation has ever been found, and the missing hour remains an unsolved mystery.",
  },
  {
    id: "f66a7eb8-4f2c-4be4-9f98-b92f5284cf19",
    title: "Vanishing Pyramid",
    author: "Dr. Emilio Vargas",
    dateOfPublication: "1985-09-30",
    text: "In 1937, a hidden pyramid was discovered deep in the Amazon rainforest, covered in hieroglyphs that resembled no known civilization. It was documented and photographed extensively. However, when archaeologists returned six months later, the structure had vanished, leaving only untouched jungle behind.",
  },
  {
    id: "a12d4c7b-6a95-482a-8b5c-2ffb7e34239c",
    title: "Eternal Storm of 1689",
    author: "Captain Isaac Redgrave",
    dateOfPublication: "1992-06-14",
    text: "A ship sailing the Atlantic in 1689 reported being caught in a storm that lasted for 30 days straight, with no breaks in the wind or rain. The crew swore they saw ghostly figures in the clouds and heard whispers in the thunder. When they finally escaped, the ship had aged as if decades had passed.",
  },
  {
    id: "b9f74a5c-77eb-4d69-bc8f-e9b5e59b44e3",
    title: "Midnight Sun of 1550",
    author: "Astronomer Giovanni Bellucci",
    dateOfPublication: "1982-04-03",
    text: "For an entire week in June 1550, the sun never set over Europe, casting an eerie glow even at midnight. Farmers claimed their crops grew twice as fast, while some people reported strange visions. On the eighth day, normal night returned as if nothing had happened.",
  },
  {
    id: "c3d45a61-2a92-453a-9b3b-fb3e9e1e35a7",
    title: "Ghost Fleet of 1801",
    author: "Admiral Charles Montague",
    dateOfPublication: "1990-12-25",
    text: "A fleet of warships was spotted sailing through the English Channel in perfect formation, but when approached, the vessels vanished into mist. Reports of the ghostly fleet persisted for years, always appearing before major naval battles, leading many to believe it was a warning from lost sailors.",
  },
  {
    id: "d7a0e916-8175-4c9e-9fa6-7bc21e0b65e2",
    title: "Day the Stars Fell",
    author: "Dr. Eleanor Whitmore",
    dateOfPublication: "1981-11-10",
    text: "On September 29, 1893, thousands of bright lights were seen falling from the sky across the globe. Unlike meteors, they did not burn up but instead landed gently on the ground. When examined, they vanished into thin air, leaving no trace. No scientific theory has ever explained the event.",
  },
];

module.exports = mockArticles;
